//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colruyt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lijst_Product
    {
        public int Lijst_Product_ID { get; set; }
        public Nullable<int> Lijst_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
    
        public virtual Lijst Lijst { get; set; }
        public virtual Product Product { get; set; }
    }
}
