//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colruyt_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lijst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lijst()
        {
            this.Lijst_Product = new HashSet<Lijst_Product>();
        }
    
        public int Lijst_ID { get; set; }
        public string Naam { get; set; }
        public Nullable<System.DateTime> DatumAangemaakt { get; set; }
        public Nullable<int> Login_ID { get; set; }
    
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lijst_Product> Lijst_Product { get; set; }
    }
}
